"""Enumeraciones de riesgo y modo de trading."""

from enum import StrEnum


class TradingMode(StrEnum):
    PAPER = "paper"
    LIVE = "live"


class RejectionCode(StrEnum):
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    INSUFFICIENT_POSITION = "INSUFFICIENT_POSITION"
    MAX_POSITION_SIZE = "MAX_POSITION_SIZE"
    MAX_EXPOSURE = "MAX_EXPOSURE"
    MAX_UNDERLYING_EXPOSURE = "MAX_UNDERLYING_EXPOSURE"
    MAX_OPEN_POSITIONS = "MAX_OPEN_POSITIONS"
    MAX_POSITIONS_PER_UNDERLYING = "MAX_POSITIONS_PER_UNDERLYING"
    MAX_TOTAL_PREMIUM = "MAX_TOTAL_PREMIUM"
    MIN_CASH_RESERVE = "MIN_CASH_RESERVE"
    MAX_DAILY_LOSS = "MAX_DAILY_LOSS"
    MAX_WEEKLY_LOSS = "MAX_WEEKLY_LOSS"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    MAX_CONSECUTIVE_LOSSES = "MAX_CONSECUTIVE_LOSSES"
    DAILY_TRADE_LIMIT = "DAILY_TRADE_LIMIT"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_QUOTE = "INVALID_QUOTE"
    STALE_QUOTE = "STALE_QUOTE"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    LOW_VOLUME = "LOW_VOLUME"
    EXPIRATION_TOO_NEAR = "EXPIRATION_TOO_NEAR"
    EXPIRATION_TOO_FAR = "EXPIRATION_TOO_FAR"
    ASSET_NOT_AUTHORIZED = "ASSET_NOT_AUTHORIZED"
    MARKET_CLOSED = "MARKET_CLOSED"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    NAKED_SHORT_FORBIDDEN = "NAKED_SHORT_FORBIDDEN"
    LIVE_TRADING_DISABLED = "LIVE_TRADING_DISABLED"
    MISSING_DATA = "MISSING_DATA"
    RISK_CALCULATION_ERROR = "RISK_CALCULATION_ERROR"
    ORDER_REJECTED_REPEATEDLY = "ORDER_REJECTED_REPEATEDLY"


class CircuitBreakerReason(StrEnum):
    DAILY_LOSS = "DAILY_LOSS"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    API_ERRORS = "API_ERRORS"
    STALE_MARKET_DATA = "STALE_MARKET_DATA"
    ABNORMAL_MOVE = "ABNORMAL_MOVE"
    PORTFOLIO_MISMATCH = "PORTFOLIO_MISMATCH"
    REPEATED_REJECTIONS = "REPEATED_REJECTIONS"
    EXPOSURE_UNCALCULABLE = "EXPOSURE_UNCALCULABLE"
    MANUAL = "MANUAL"
    EMERGENCY_STOP = "EMERGENCY_STOP"
